language: python
python:
  - "3.5"
  - "3.6"

services:
  - mysql

env:
  - BACKLOG_CONFIG=$TRAVIS_BUILD_DIR/travis/config.yaml

install:
  # Test dependencies
  - pip install 'pytest==3.7.4'
  # Project dependencies
  - pip install -U git+git://github.com/EBI-Metagenomics/emg-backlog-schema.git
  - pip install -U git+git://github.com/EBI-Metagenomics/ena-api-handler.git
  - pip install -U  .

  # Setup database
  - mysql -e 'CREATE DATABASE emg_backlog_2;'
  - emgbacklog migrate --database=default
  - mysql -u root --password="" --database=emg_backlog_2 < travis/biomes.sql

script:
  - pytest --reruns 3 --reruns-delay 1

after_success:
  - pip install codacy-coverage
  - python-codacy-coverage -r coverage.xml
